"""Function name mapping for OneControl IDS CAN protocol.

Maps numeric FUNCTION_NAME values to friendly device names.
Complete mapping of all 445 function names from IDS.Core.IDS_CAN.Descriptors (4.6.4.0).

Reference: INTERNALS.md § Device Metadata Retrieval
"""

from __future__ import annotations

# fmt: off
FUNCTION_NAMES: dict[int, str] = {
    # System & Diagnostic
    1: "Diagnostic Tool",
    2: "MyRV Tablet",

    # Water & Plumbing
    3: "Gas Water Heater",
    4: "Electric Water Heater",
    5: "Water Pump",
    67: "Fresh Tank",
    68: "Grey Tank",
    69: "Black Tank",
    70: "Fuel Tank",
    71: "Generator Fuel Tank",
    72: "Auxiliary Fuel Tank",
    73: "Front Bath Grey Tank",
    74: "Front Bath Fresh Tank",
    75: "Front Bath Black Tank",
    76: "Rear Bath Grey Tank",
    77: "Rear Bath Fresh Tank",
    78: "Rear Bath Black Tank",
    79: "Main Bath Grey Tank",
    80: "Main Bath Fresh Tank",
    81: "Main Bath Black Tank",
    82: "Galley Grey Tank",
    83: "Galley Fresh Tank",
    84: "Galley Black Tank",
    85: "Kitchen Grey Tank",
    86: "Kitchen Fresh Tank",
    87: "Kitchen Black Tank",
    107: "Water Tank Heater",
    173: "Fresh Tank Heater",
    174: "Grey Tank Heater",
    175: "Black Tank Heater",
    270: "Tank Heater",
    295: "Water Heater",
    296: "Water Heaters",
    303: "Waste Valve",
    381: "Holding Tanks Heater",
    428: "Fresh Tank Valve",
    429: "Grey Tank Valve",
    430: "Black Tank Valve",
    431: "Front Bath Grey Tank Valve",
    432: "Front Bath Fresh Tank Valve",
    433: "Front Bath Black Tank Valve",
    434: "Rear Bath Grey Tank Valve",
    435: "Rear Bath Fresh Tank Valve",
    436: "Rear Bath Black Tank Valve",
    437: "Main Bath Grey Tank Valve",
    438: "Main Bath Fresh Tank Valve",
    439: "Main Bath Black Tank Valve",
    440: "Galley Bath Grey Tank Valve",
    441: "Galley Bath Fresh Tank Valve",
    442: "Galley Bath Black Tank Valve",
    443: "Kitchen Bath Grey Tank Valve",
    444: "Kitchen Bath Fresh Tank Valve",
    445: "Kitchen Bath Black Tank Valve",

    # Ventilation & Vent Covers
    6: "Bath Vent",
    93: "Bath Vent Cover",
    110: "Vent Cover",
    111: "Front Bedroom Vent Cover",
    112: "Bedroom Vent Cover",
    113: "Front Bathroom Vent Cover",
    114: "Main Bathroom Vent Cover",
    115: "Rear Bathroom Vent Cover",
    116: "Kitchen Vent Cover",
    117: "Living Room Vent Cover",
    264: "Fan",
    265: "Bath Fan",
    266: "Rear Fan",
    267: "Front Fan",
    268: "Kitchen Fan",
    269: "Ceiling Fan",
    398: "Computer Fan",
    399: "Battery Fan",

    # Lights - General
    7: "Light",
    8: "Flood Light",
    9: "Work Light",
    47: "Security Light",
    48: "Porch Light",
    49: "Awning Light",
    61: "Ceiling Light",
    62: "Entry Light",
    63: "Bed Ceiling Light",
    64: "Bedroom Lav Light",
    65: "Shower Light",
    66: "Galley Light",
    120: "Patio Light",
    121: "Hutch Light",
    122: "Scare Light",
    123: "Dinette Light",
    124: "Bar Light",
    125: "Overhead Light",
    126: "Overhead Bar Light",
    127: "Foyer Light",
    128: "Ramp Door Light",
    129: "Entertainment Light",
    130: "Rear Entry Door Light",
    131: "Ceiling Fan Light",
    132: "Overhead Fan Light",
    143: "Exterior Light",
    144: "Lower Accent Light",
    145: "Upper Accent Light",
    146: "DS Security Light",
    147: "ODS Security Light",
    149: "Hitch Light",
    169: "Front Cap Light",
    170: "Step Light",
    171: "DS Flood Light",
    172: "Interior Light",
    177: "Stall Light",
    178: "Main Light",
    179: "Bath Light",
    180: "Bunk Light",
    181: "Bed Light",
    182: "Cabinet Light",
    195: "Compartment Light",
    196: "Trunk Light",
    220: "Accent Light",
    271: "Front Ceiling Light",
    272: "Rear Ceiling Light",
    273: "Cargo Light",
    274: "Fascia Light",
    275: "Slide Ceiling Light",
    276: "Slide Overhead Light",
    277: "Decor Light",
    278: "Reading Light",
    279: "Front Reading Light",
    280: "Rear Reading Light",
    289: "Mens Light",
    290: "Womens Light",
    291: "Service Light",
    292: "ODS Flood Light",
    293: "Underbody Accent Light",
    294: "Speaker Light",
    305: "Front Locker Light",
    306: "Rear Locker Light",
    308: "Rock Light",
    309: "Chassis Light",
    310: "Exterior Shower Light",
    311: "Living Room Accent Light",
    312: "Rear Flood Light",
    313: "Passenger Flood Light",
    314: "Driver Flood Light",
    360: "Jacks Lights",
    362: "Interior Step Light",
    363: "Exterior Step Light",
    366: "Soffit Light",
    392: "Central Lights",
    393: "Right Side Lights",
    394: "Left Side Lights",
    395: "Right Scene Lights",
    396: "Left Scene Lights",
    397: "Rear Scene Lights",
    402: "Dump Light",
    410: "Theater Lights",
    411: "Utility Cabinet Light",
    412: "Chase Light",
    413: "Floor Lights",
    414: "RTT Light",

    # Bedroom Lights
    10: "Front Bedroom Ceiling Light",
    11: "Front Bedroom Overhead Light",
    12: "Front Bedroom Vanity Light",
    13: "Front Bedroom Sconce Light",
    14: "Front Bedroom Loft Light",
    15: "Rear Bedroom Ceiling Light",
    16: "Rear Bedroom Overhead Light",
    17: "Rear Bedroom Vanity Light",
    18: "Rear Bedroom Sconce Light",
    19: "Rear Bedroom Loft Light",
    20: "Loft Light",
    56: "Bunk Room Light",
    57: "Bedroom Light",
    222: "Bedroom Accent Light",
    223: "Front Bedroom Accent Light",
    227: "Rear Bedroom Accent Light",

    # Hall Lights
    21: "Front Hall Light",
    22: "Rear Hall Light",
    55: "Hall Light",

    # Bathroom Lights
    23: "Front Bathroom Light",
    24: "Front Bathroom Vanity Light",
    25: "Front Bathroom Ceiling Light",
    26: "Front Bathroom Shower Light",
    27: "Front Bathroom Sconce Light",
    28: "Rear Bathroom Vanity Light",
    29: "Rear Bathroom Ceiling Light",
    30: "Rear Bathroom Shower Light",
    31: "Rear Bathroom Sconce Light",
    50: "Bathroom Light",
    51: "Bathroom Vanity Light",
    52: "Bathroom Ceiling Light",
    53: "Bathroom Shower Light",
    54: "Bathroom Sconce Light",
    221: "Bathroom Accent Light",

    # Kitchen Lights
    32: "Kitchen Ceiling Light",
    33: "Kitchen Sconce Light",
    34: "Kitchen Pendants Light",
    35: "Kitchen Range Light",
    36: "Kitchen Counter Light",
    37: "Kitchen Bar Light",
    38: "Kitchen Island Light",
    39: "Kitchen Chandelier Light",
    40: "Kitchen Under Cabinet Light",
    59: "Kitchen Light",
    225: "Kitchen Accent Light",
    406: "Kitchen Pendant Light",

    # Living Room Lights
    41: "Living Room Ceiling Light",
    42: "Living Room Sconce Light",
    43: "Living Room Pendants Light",
    44: "Living Room Bar Light",
    58: "Living Room Light",

    # Garage Lights
    45: "Garage Ceiling Light",
    46: "Garage Cabinet Light",
    224: "Garage Accent Light",

    # Lounge & Patio Lights
    60: "Lounge Light",
    226: "Patio Accent Light",

    # Awning Lights
    385: "Patio Awning Light",
    386: "Garage Awning Light",
    387: "Rear Awning Light",
    388: "Side Awning Light",
    389: "Slide Awning Light",
    391: "Front Awning Light",

    # Landing Gear & Stabilizers
    88: "Landing Gear",
    89: "Front Stabilizer",
    90: "Rear Stabilizer",
    106: "Level Up Leveler",
    109: "Leveler",
    118: "Four Leg Truck Camper Leveler",
    119: "Six Leg Hall Effect EJ Leveler",
    141: "Jacks",
    142: "Leveler 2",
    187: "Level Up Unity",
    188: "TT Leveler",
    189: "Travel Trailer Leveler",
    190: "Fifth Wheel Leveler",
    250: "Left Stabilizer",
    251: "Right Stabilizer",
    252: "Stabilizer",
    404: "Base Camp Leveler",

    # Lifts
    91: "TV Lift",
    92: "Bed Lift",
    286: "Bed Tilt",
    287: "Front Bed Tilt",
    288: "Rear Bed Tilt",
    316: "Roof Lift",

    # Doors & Locks
    94: "Door Lock",
    213: "Bathroom Door Lock",
    214: "Bedroom Door Lock",
    215: "Front Door Lock",
    216: "Garage Door Lock",
    217: "Main Door Lock",
    218: "Patio Door Lock",
    219: "Rear Door Lock",
    263: "Ramp Door",

    # Generator & Power
    95: "Generator",
    191: "Fuel Pump",
    253: "Solar",
    254: "Solar Power",
    255: "Battery",
    256: "Main Battery",
    257: "Aux Battery",
    258: "Shore Power",
    259: "AC Power",
    260: "AC Mains",
    261: "Aux Power",
    262: "Outputs",
    307: "Rear Aux Power",
    317: "Yeti Package",
    318: "Propane Locker",
    355: "Auxiliary Battery",
    356: "Chassis Battery",
    357: "House Battery",
    358: "Kitchen Battery",
    359: "Electronic Sway Control",
    367: "Battery Bank",
    368: "RV Battery",
    369: "Solar Battery",
    370: "Tongue Battery",
    374: "Lead Acid",
    375: "Liquid Lead Acid",
    376: "Gel Lead Acid",
    377: "AGM Absorbent Glass Mat",
    378: "Lithium",
    382: "Inverter",
    383: "Battery Heat",
    384: "Camera Power",

    # Slides
    96: "Slide",
    97: "Main Slide",
    98: "Bedroom Slide",
    99: "Galley Slide",
    100: "Kitchen Slide",
    101: "Closet Slide",
    102: "Optional Slide",
    103: "Door Side Slide",
    104: "Off Door Slide",
    133: "Bunk Slide",
    134: "Bed Slide",
    135: "Wardrobe Slide",
    136: "Entertainment Slide",
    137: "Sofa Slide",
    148: "Slide In Slide",
    299: "Slide If Equip",
    315: "Bathroom Slide",
    380: "Dinette Slide",
    400: "Right Slide Room",
    401: "Left Slide Room",
    407: "Door Side Sofa Slide",
    408: "Off Door Side Sofa Slide",
    409: "Rear Bed Slide",

    # Awnings
    105: "Awning",
    138: "Patio Awning",
    139: "Rear Awning",
    140: "Side Awning",
    300: "Awning If Equip",
    319: "Garage Awning",
    361: "Awning Sensor",
    379: "Front Awning",
    390: "Slide Awning",

    # Touchscreens & Networking
    108: "MyRV Touchscreen",
    183: "Network Bridge",
    184: "Ethernet Bridge",
    185: "WiFi Bridge",
    186: "In Transit Power Disconnect",
    297: "AquaFi",
    298: "Connect Anywhere",
    304: "Tire Linc",
    320: "Monitor Panel",
    321: "Camera",
    322: "Jayco AUS TBB GW",
    323: "Gateway RVLink",
    353: "LOCAP Gateway",
    354: "Bootloader",
    364: "WiFi Booster",
    403: "Base Camp Touchscreen",

    # Entertainment
    150: "Clock",
    151: "TV",
    152: "DVD",
    153: "Blu Ray",
    154: "VCR",
    155: "PVR",
    156: "Cable",
    157: "Satellite",
    158: "Audio",
    159: "CD Player",
    160: "Tuner",
    161: "Radio",
    162: "Speakers",
    163: "Game",
    164: "Clock Radio",
    165: "Aux",
    197: "Bar TV",
    198: "Bathroom TV",
    199: "Bedroom TV",
    200: "Bunk Room TV",
    201: "Exterior TV",
    202: "Front Bathroom TV",
    203: "Front Bedroom TV",
    204: "Garage TV",
    205: "Kitchen TV",
    206: "Living Room TV",
    207: "Loft TV",
    208: "Lounge TV",
    209: "Main TV",
    210: "Patio TV",
    211: "Rear Bathroom TV",
    212: "Rear Bedroom TV",
    228: "Bedroom Radio",
    229: "Bunk Room Radio",
    230: "Exterior Radio",
    231: "Front Bedroom Radio",
    232: "Garage Radio",
    233: "Kitchen Radio",
    234: "Living Room Radio",
    235: "Loft Radio",
    236: "Patio Radio",
    237: "Rear Bedroom Radio",
    238: "Bedroom Entertainment System",
    239: "Bunk Room Entertainment System",
    240: "Entertainment System",
    241: "Exterior Entertainment System",
    242: "Front Bedroom Entertainment System",
    243: "Garage Entertainment System",
    244: "Kitchen Entertainment System",
    245: "Living Room Entertainment System",
    246: "Loft Entertainment System",
    247: "Main Entertainment System",
    248: "Patio Entertainment System",
    249: "Rear Bedroom Entertainment System",
    365: "Audible Alert",

    # Climate Zones
    166: "Climate Zone",
    167: "Fireplace",
    168: "Thermostat",
    192: "Main Climate Zone",
    193: "Bedroom Climate Zone",
    194: "Garage Climate Zone",
    281: "Living Room Climate Zone",
    282: "Front Living Room Climate Zone",
    283: "Rear Living Room Climate Zone",
    284: "Front Bedroom Climate Zone",
    285: "Rear Bedroom Climate Zone",

    # LP Tanks
    176: "LP Tank",
    345: "LP Tank RV",
    346: "LP Tank Home",
    347: "LP Tank Cabin",
    348: "LP Tank BBQ",
    349: "LP Tank Grill",
    350: "LP Tank Submarine",
    351: "LP Tank Other",

    # Conditional Equipment
    301: "Awning Light If Equip",
    302: "Interior Light If Equip",

    # Temperature Sensors
    324: "Accessory Temperature",
    325: "Accessory Refrigerator",
    326: "Accessory Fridge",
    327: "Accessory Freezer",
    328: "Accessory External",
    330: "Temp Refrigerator",
    331: "Temp Refrigerator Home",
    332: "Temp Freezer",
    333: "Temp Freezer Home",
    334: "Temp Cooler",
    335: "Temp Kitchen",
    336: "Temp Living Room",
    337: "Temp Bedroom",
    338: "Temp Master Bedroom",
    339: "Temp Garage",
    340: "Temp Basement",
    341: "Temp Bathroom",
    342: "Temp Storage Area",
    343: "Temp Drivers Area",
    344: "Temp Bunks",

    # Brake Controllers
    329: "Trailer Brake Controller",
    352: "Anti Lock Braking System",
    371: "Axle1 Brake Controller",
    372: "Axle2 Brake Controller",
    373: "Axle3 Brake Controller",

    # Power Shades
    415: "Upper Power Shades",
    416: "Lower Power Shades",
    417: "Living Room Power Shades",
    418: "Bedroom Power Shades",
    419: "Bathroom Power Shades",
    420: "Bunk Power Shades",
    421: "Loft Power Shades",
    422: "Front Power Shades",
    423: "Rear Power Shades",
    424: "Main Power Shades",
    425: "Garage Power Shades",
    426: "Door Side Power Shades",
    427: "Off Door Side Power Shades",

    # Refrigerator
    405: "Refrigerator",
}
# fmt: on


def get_friendly_name(function_name: int, function_instance: int = 0) -> str:
    """Return a friendly name for a (function_name, function_instance) pair.

    Appends the instance number only when > 0 (multiple devices of same type).
    """
    base = FUNCTION_NAMES.get(function_name, f"Unknown Device {function_name}")
    return f"{base} {function_instance}" if function_instance > 0 else base


def to_entity_id(friendly_name: str) -> str:
    """Convert a friendly name to a valid HA entity_id suffix.

    Example: "Living Room Ceiling Light" → "living_room_ceiling_light"
    """
    import re

    return re.sub(r"[^a-z0-9]+", "_", friendly_name.lower()).strip("_")
