name: Bug Report
description: Something isn't working correctly
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before filing, please check the [open issues](../../issues) to avoid duplicates.

  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Version
      placeholder: "e.g. 2026.2.3"
    validations:
      required: true

  - type: input
    id: integration_version
    attributes:
      label: Integration Version
      description: Found in HACS or the integration's About page
      placeholder: "e.g. 2.7.3"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device Model
      description: Device model and firmware if known
      placeholder: "e.g. see device label or app"
    validations:
      required: true

  - type: dropdown
    id: adapter
    attributes:
      label: Bluetooth Adapter
      options:
        - ESPHome Bluetooth Proxy
        - USB HCI adapter (direct, no proxy)
        - Built-in adapter (direct, no proxy)
        - Multiple / mixed
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Enable debug logging first by adding to `configuration.yaml`:
        ```yaml
        logger:
          logs:
            custom_components.onecontrol: debug
        ```
        Then paste the relevant log lines here.
      render: text
    validations:
      required: true
